# This file was generated by GoReleaser. DO NOT EDIT.
cask "cli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "3d311bec50dddeb6d70379cf71babf6aa935127ad2a5325b32fd80b8d4863c49"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e74cf400bc99e7275ae8a399f7e607ed8a1bfa5a4aa8539c3568e9237ef56d28"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ebf89b79741061c712d16a257247e945c9bc583967fa4d2c001ce17197e9a21"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "03d07e1671cacc4d7c2d985974dcecbef5849b97d8eb34afe9a4d44ea731bb81"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz"
    end
  end

  name "cli"
  desc "Tools for working with slingshot pipelines"
  homepage "https://github.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cli"

  # No zap stanza required

end
