# This file was generated by GoReleaser. DO NOT EDIT.
cask "slingshot" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "9d959c7bef9e93e9a5bba1dd4b26eccf38ac6edc32a64504021db0cd6d4f4269"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9204e0e04bf7f425aaddb47078606d58ba591caf733c6d1556236659e1b0aa30"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "033e86de1c7a3ec4ce3aedbb834cadff7a086f0685e703643c97b18be5ba5c2a"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "973ce61b95e82831dd18854555f6d5602b28e2c434ebf8f27c34c76868875acb"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz"
    end
  end

  name "slingshot"
  desc "Tools for working with slingshot pipelines"
  homepage "https://github.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slingshot"

  # No zap stanza required

end
