# This file was generated by GoReleaser. DO NOT EDIT.
cask "slingshot" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "50d1b95d8331af2b891a17f6151c35f13945e7f4d331823328c215097a5e1cfe"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c95ed66f1f768d6cd526e59571393bfe5a4962a5d7d997c7ed181fb60c43f109"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3a0ae42400f605bdb244c7f82d7ddd6a71a34bd70444261c1d97f06a21f421e"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4852999151822cda099b5345db01819ed54cfd3de96325b7e59e12061b3c56ac"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz"
    end
  end

  name "slingshot"
  desc "Tools for working with slingshot pipelines"
  homepage "https://github.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slingshot"

  # No zap stanza required

end
