# This file was generated by GoReleaser. DO NOT EDIT.
cask "slingshot" do
  binary "slingshot"

  # Maps Cobra's runtime completion logic directly into Homebrew
  generate_completions_from_executable "#{staged_path}/slingshot", "completion", shells: [:bash, :zsh, :fish]

  version "0.1.9"

  on_macos do
    on_intel do
      sha256 "926b741985329e9d7749f481faa88670330216cf9a9e88d8aa28ea928f1fe662"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a54781848cf098154242fcfcefc8008c21ca52edc7bf7f24fe08c1b2b3385c16"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4bf4ac09c9345d4663447f142be626254e484d327e9de418e54f85ae4fe0732b"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "37ebbe927a50b61232b5fd867738f7f20f2e6de848520e12a1c2bfb951af434b"
      url "https://github.com/slingshot-pipelines/cli/releases/download/v#{version}/cli_Linux_arm64.tar.gz"
    end
  end

  name "slingshot"
  desc "Tools for working with slingshot pipelines"
  homepage "https://github.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slingshot"

  # No zap stanza required

end
